### ISSUE TITLE
Current release doesn't work with Go modules

### ISSUE THREAD

**Issue by ctessum** [caltechlibrary/bibtex#3]
When trying to use this package as a dependency with the new Go modules, it fails by default, e.g.:

```bash
user@machine:~/my_program$ go build 
go: finding github.com/caltechlibrary/bibtex v0.0.7
go: downloading github.com/caltechlibrary/bibtex v0.0.7
build github.com/user/my_program: cannot find module for path github.com/caltechlibrary/tok
```
This appears to be because the `tok` package has been moved since the most recent release. The following command works as a workaround.

```bash
user@machine:~/my_program$ go get -u github.com/caltechlibrary/bibtex@ca44da07ce7bff47b372002f04da9c0c1182c86c
go: finding github.com/caltechlibrary/bibtex ca44da07ce7bff47b372002f04da9c0c1182c86c
go: downloading github.com/caltechlibrary/bibtex v0.0.6-0.20180828175021-ca44da07ce7b
```

I think a more permanent solution, however, would be to create a new release based on the master. This should cause things to work by default.

**Comment by rsdoiel** [comment]
Thanks for this report! The tok package is deprecated and I missed the use of it.  I'll fix it and then push out an updated.  I'll let you know when I'm done by closing this issue. Again thanks for giving this a try.

All the best,

Robert

**Comment by rsdoiel** [comment]
Ok, I think we're good.  I've released the new package (which indeed solves your immediate issue), update the cli package references to support the current released version. Verified I can still install from scratch using `go get -u github.com/caltechlibrary/bibtex/...`. Removed an JS experiment since Go v1.11 starts the cycle of getting WASM support.  Please let me know if you run into anything else and thank you for both the bug report and interest! All the best, Robert
